### ISSUE TITLE
[issue]: Fedora 35 live iso "hijacks" temporarily the vgubuntu-root

### ISSUE THREAD

**Issue by stegrams** [ventoy/Ventoy#1524]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.71

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

SP

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://download.fedoraproject.org/pub/fedora/linux/releases/35/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-35-1.2.iso

### What happened?

During my main system session, this is how my partitions show from blivet:

![blivet-vgubuntu-ubuntu](https://user-images.githubusercontent.com/1965285/159249200-83122685-00d6-4d60-bbe1-8f38d16bbe4a.png)

Now, when in Fedora live session, this is how the same partitions look like:

![blivet-vgubuntu-fedora-live](https://user-images.githubusercontent.com/1965285/159277576-0a7459d6-8d2b-42c2-ae34-26ccaa51e74d.png)

Fortunately, this is a temporary setup until the next boot, but it stops me from resizing the vgubuntu-root. 

OS: Ubuntu 20.04.4 LTS x86_64 
Host: Inspiron 3580 
Kernel: 5.13.0-35-generic 
Shell: bash 5.0.17 
DE: GNOME 
WM: Mutter 
CPU: Intel i7-8565U (8) @ 4.600GHz 
GPU: Intel UHD Graphics 620 
GPU: AMD ATI Radeon R5 M230 / R7 M26 
Memory: 15876MiB

**Comment by ventoy** [comment]
Does it display normal if you don't use Ventoy to boot the ISO file ? (e.g. Write the Fedora live ISO to the same USB with Rufus and boot it)

**Comment by stegrams** [comment]
Yes it does. Using Fedora Media Writer 4.2.2 from dl.flathub.org I have this result:

![blivet-vgubuntu-fedora-with-fedora-media-writer](https://user-images.githubusercontent.com/1965285/159241648-a99c7887-ca39-49a5-83f6-d79cf7e7f098.png)

**Comment by ventoy** [comment]
When boot from Ventoy, Ventoy will create a dm device based on the ISO file.
So in the second screenshot, the 1.87GB  iso9660 device shoule be  `/dev/mapper/ventoy` which should be linked to  `/dev/dm-0`
I don't known why it recognize it as the `vgubuntu-root`.
Run `vgs` command in the shell and check the result.

**Comment by stegrams** [comment]
```
[liveuser@localhost-live ~]$ sudo vgs
  VG       #PV #LV #SN Attr   VSize    VFree 
  vg_sda     1   3   0 wz--n- <931.51g 10.80g
  vgubuntu   1   2   0 wz--n-  237.97g 24.00m
```

**Comment by stegrams** [comment]
```
[liveuser@localhost-live ~]$ lsblk
NAME                     MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0                      7:0    0   1.8G  1 loop 
loop1                      7:1    0   7.5G  1 loop 
├─live-rw                253:6    0   7.5G  0 dm   /
└─live-base              253:7    0   7.5G  1 dm   
loop2                      7:2    0    32G  0 loop 
└─live-rw                253:6    0   7.5G  0 dm   /
sda                        8:0    0 931.5G  0 disk 
└─sda1                     8:1    0 931.5G  0 part 
  ├─vg_sda-lv_guest_home 253:2    0 465.7G  0 lvm  
  ├─vg_sda-lv_ubu_home   253:3    0   230G  0 lvm  
  └─vg_sda-lv_ubu_docker 253:4    0   225G  0 lvm  
sdb                        8:16   1  28.9G  0 disk 
├─sdb1                     8:17   1  20.9G  0 part 
├─sdb2                     8:18   1    32M  0 part 
└─sdb3                     8:19   1     8G  0 part /run/media/liveuser/store
sr0                       11:0    1  1024M  0 rom  
zram0                    252:0    0     8G  0 disk [SWAP]
nvme0n1                  259:0    0 238.5G  0 disk 
├─nvme0n1p1              259:1    0   512M  0 part 
└─nvme0n1p2              259:2    0   238G  0 part 
  ├─vgubuntu-root        253:0    0   237G  0 lvm  /run/initramfs/live
  └─vgubuntu-swap_1      253:1    0   976M  0 lvm  

```

**Comment by ventoy** [comment]
It shows  `vgubuntu-root`  `237G`  in lsblk, but show 1.87G in blivet-gui, strange.

**Comment by erya777** [comment]
Hi @ventoy I've also encountered issue related to this one.
I was trying to run Fedora installer on PC that had a drive with LUKS container on LVM (so LVM structure itself is visible to OS without decryption) and Fedora installer wouldn't load giving an error regarding some mapping issue for live image.
I was able to use clean USB drive with the same Fedora bootable ISO at that time.
After that I tried to understand why it happened and it looks like there is some issue with Ventoy not creating dynamic mappings correctly or something when booting Fedora ISO.
I'm running tests on KVM machine using latest ventoy CI build on my real USB-drive configured to passthrough.
This is what happens when I'm booting Fedora ISO with Ventoy when there are no partitions on connected disk drive:
```
[root@localhost-live ~]# lsblk 
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
loop0         7:0    0  1.8G  1 loop 
loop1         7:1    0  7.5G  1 loop 
├─live-rw   253:1    0  7.5G  0 dm   /
└─live-base 253:2    0  7.5G  1 dm   
loop2         7:2    0   32G  0 loop 
└─live-rw   253:1    0  7.5G  0 dm   /
sda           8:0    0   20G  0 disk 
sdb           8:16   1 58.2G  0 disk 
├─sdb1        8:17   1 58.2G  0 part 
└─sdb2        8:18   1   32M  0 part 
zram0       252:0    0  7.6G  0 disk [SWAP]

[root@localhost-live ~]# ls -la /dev/mapper/
total 0
drwxr-xr-x.  2 root root     100 Apr 28  2022 .
drwxr-xr-x. 20 root root    4060 Apr 28  2022 ..
crw-------.  1 root root 10, 236 Apr 28  2022 control
lrwxrwxrwx.  1 root root       7 Apr 28  2022 live-base -> ../dm-2
lrwxrwxrwx.  1 root root       7 Apr 28  2022 live-rw -> ../dm-1

[root@localhost-live ~]# blkid 
/dev/loop1: LABEL="Anaconda" UUID="8e88a3a2-d9af-4034-9ad9-594e1a0d514b" BLOCK_SIZE="4096" TYPE="ext4"
/dev/mapper/live-rw: LABEL="Anaconda" UUID="8e88a3a2-d9af-4034-9ad9-594e1a0d514b" BLOCK_SIZE="4096" TYPE="ext4"
/dev/sdb2: SEC_TYPE="msdos" LABEL_FATBOOT="VTOYEFI" LABEL="VTOYEFI" UUID="1234-2324" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="4123adb-20"
/dev/sdb1: LABEL="USB_FLASH" BLOCK_SIZE="512" UUID="12314123131AB" TYPE="ntfs" PARTUUID="123456-01"
/dev/mapper/live-base: LABEL="Anaconda" UUID="8e88a3a2-d9af-4034-9ad9-594e1a0d514b" BLOCK_SIZE="4096" TYPE="ext4"
/dev/loop0: TYPE="squashfs"
/dev/dm-0: BLOCK_SIZE="2048" UUID="2021-10-26-06-03-59-00" LABEL="Fedora-WS-Live-35-1-2" TYPE="iso9660" PTUUID="14fc2edf" PTTYPE="dos"
/dev/zram0: LABEL="zram0" UUID="a5eaa013-039e-42a2-99e2-7451d97e464c" TYPE="swap"

[root@localhost-live ~]# dmsetup ls
live-base	(253:2)
live-rw	(253:1)
ventoy	(253:0)
[root@localhost-live ~]# dmsetup info ventoy
Name:              ventoy
State:             ACTIVE (READ-ONLY)
Read Ahead:        256
Tables present:    LIVE
Open count:        1
Event number:      0
Major, minor:      253, 0
Number of targets: 1

[root@localhost-live ~]# mount | grep ven
/dev/mapper/ventoy on /run/initramfs/live type iso9660 (ro,relatime,nojoliet,check=s,map=n,blocksize=2048,iocharset=utf8)

[root@localhost-live ~]# gdisk /dev/sda -l
GPT fdisk (gdisk) version 1.0.8

Partition table scan:
  MBR: not present
  BSD: not present
  APM: not present
  GPT: not present

```

Now I will create single LVM partition with 1 LV and try to boot again using same Fedora ISO:

```
[root@localhost-live ~]# lsblk /dev/sda
NAME                MAJ:MIN RM SIZE RO TYPE MOUNTPOINTS
sda                   8:0    0  20G  0 disk 
└─sda1                8:1    0  20G  0 part 
  └─vg_test-lv_test 253:3    0  20G  0 lvm 
```
  
  
![Screenshot from 2022-04-28 15-19-56](https://user-images.githubusercontent.com/55016617/165750632-ad7c8cff-ca9d-4464-9c94-65a2f4859f5a.png)

Fedora ISO will not boot anymore using Ventoy, but will boot using simple bootable USB with Fedora ISO.

**Comment by ventoy** [comment]
@erya777 
I made some modification. Please try the latest CI release after it finish.

**Comment by erya777** [comment]
Yes, looks like it's fixed now, I am able to boot Fedora iso and don't see any strange behaviour with mappings.
Thanks!

**Comment by ventoy** [comment]
@stegrams 
You can also try the latest CI release.

**Comment by stegrams** [comment]
Using the VentoyGUI.x86_64, I updated my USB stick to 1.0.74. Rebooting with Fedora 35, I still see the live fs latched on the vgubuntu-root partition, although meanwhile I created a new one (btw...).

This is the current blivet-gui view from the Ventoy Fedora session:
![Screenshot from 2022-04-28 15-06-09](https://user-images.githubusercontent.com/1965285/166084062-a73ffb05-de9d-42c7-9d95-a2a5402b1d4e.png)

And this is from Media Writer 4.2.2 Fedora session:
![image](https://user-images.githubusercontent.com/1965285/166084971-35008315-0cd3-4b08-a7ec-13547f085d72.png)

**Comment by ventoy** [comment]
@stegrams 
Please use the following latest CI release (not 1.0.74)
https://github.com/ventoy/Ventoy/actions/runs/2245185023
https://www.ventoy.net/en/doc_github_ci.html

**Comment by stegrams** [comment]
@ventoy Oh, that one! Yes that did the trick, I don't see the live fs latched on any of my real partitions.
The CI version downloaded from https://github.com/ventoy/Ventoy/suites/6314354597/artifacts/226692409 looks OK from my point of view.
I suppose this issue should remain open until that version find it's way to the official releases and after testing it again, but please close it if it's ok to you.

**Comment by ventoy** [comment]
Good news!
Let's keep the issue open until 1.0.75 release.

**Comment by Windows-Guy** [comment]
I installed the ci when this was fixed and cant get the new fedoara 36 or redhat9 to boot past their black screen before the installer. It just locks up my computer.  I have to hold the power down

**Comment by ventoy** [comment]
1.0.75 release
