### ISSUE TITLE
[issue]: kickstart installation for rhel based distributions broken

### ISSUE THREAD

**Issue by ManiacTwister** [ventoy/Ventoy#1717]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.78

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB

### What happened?

When doing an kickstart installation of RHEL based distributions (Almalinux, Rocky, Fedora, etc) with an external kickstart file (for example fetched over http), ventoy modfies the ks/inst.ks kernel command line and prepends "/dev/ventoy" to it.

For example `inst.ks=http://ks.xxx.tld/xx-backup01.cfg` get `inst.ks=/dev/ventoy://ks.xxx.tld/xx-backup01.cfg`
![image](https://user-images.githubusercontent.com/893193/177759351-cde3fa6e-0a77-4834-80e8-d56921948ef3.png)

This is also true for the older `ks` parameter.

The relevant code can be found here (unfortunately i'm unable to compile ventoy myself, otherwise i would've submitted a patch):
https://github.com/ventoy/Ventoy/blob/v1.0.78/IMG/cpio/ventoy/hook/rhel7/ventoy-hook.sh#L41-L44
https://github.com/ventoy/Ventoy/blob/v1.0.78/IMG/cpio/ventoy/hook/rhel7/ventoy-hook.sh#L35-L39

and
https://github.com/ventoy/Ventoy/blob/v1.0.78/IMG/cpio/ventoy/hook/openEuler/ventoy-hook.sh#L32-L46
https://github.com/ventoy/Ventoy/blob/v1.0.78/IMG/cpio/ventoy/hook/openEuler/ventoy-hook.sh#L38-L42

**Comment by ventoy** [comment]
@ManiacTwister 
Please try this CI release: https://github.com/ventoy/Ventoy/actions/runs/2655426868
https://www.ventoy.net/en/doc_github_ci.html

**Comment by ventoy** [comment]
@ManiacTwister
The latest 1.0.79 release should fix it.

**Comment by ManiacTwister** [comment]
@ventoy thanks - i'm currently on vacation - i'll test it as soon as possible. :)

**Comment by didierm** [comment]
This is still an issue when booting e.g. the [AlmaLinux 9.2 DVD](https://ftp.belnet.be/mirrors/almalinux/9/isos/x86_64/AlmaLinux-9.2-x86_64-dvd.iso) : 
`/dev/ventoy:` gets prepended to the `inst.ks=`  parameter value, rendering a kickstart installation impossible.

(tested with Ventoy versions 1.0.79 and latest 1.0.94).

**Comment by gadh** [comment]
please reopen the bug unless its really fixed ... i encountered this also in latest version
