### ISSUE TITLE
Ventoy2Disk.exe -U is not working

### ISSUE THREAD

**Issue by undefined-moe** [ventoy/Ventoy#614]
![image](https://user-images.githubusercontent.com/29992205/100359185-2d36db80-3032-11eb-8bff-5aca224daffa.png)
![image](https://user-images.githubusercontent.com/29992205/100359224-39229d80-3032-11eb-8a76-1611fdf940a7.png)

a portable disk(hd1) is connected however

**Comment by ventoy** [comment]
please give the log.txt

**Comment by undefined-moe** [comment]
```
[2020/11/26 21:52:49.604] 
################################ Ventoy2Disk 1.0.0.2 ################################
[2020/11/26 21:52:49.605] CmdLine:<-U>
[2020/11/26 21:52:49.605] Control Flag: 0 0 1
[2020/11/26 21:52:49.606] Windows Version : Windows 10 64-bit (Build 18363)
[2020/11/26 21:52:49.606] 
===================== Enum All PhyDrives =====================
[2020/11/26 21:52:49.606] RegOpenKeyExA <SYSTEM\CurrentControlSet\Services\disk\Enum> Ret:0
[2020/11/26 21:52:49.606] RegQueryValueExA <Count> ret:0  Size:4 Value:2
[2020/11/26 21:52:49.607] GetPhysicalDriveCount: 2
[2020/11/26 21:52:49.607] Logical Drives: 0x4c
[2020/11/26 21:52:49.607] LogicalDrive:\\.\C: PhyDrive:0 Offset:677380096 ExtentLength:325042831360
[2020/11/26 21:52:49.607] C --> 0
[2020/11/26 21:52:49.608] LogicalDrive:\\.\D: PhyDrive:0 Offset:325720211456 ExtentLength:34359738368
[2020/11/26 21:52:49.608] D --> 0
[2020/11/26 21:52:49.608] LogicalDrive:\\.\G: PhyDrive:1 Offset:134238208 ExtentLength:3966258606080
[2020/11/26 21:52:49.608] G --> 1
[2020/11/26 21:52:49.609] Create file Handle:FFFFFFFF \\.\PhysicalDrive0 status:32
[2020/11/26 21:52:49.610] Create file Handle:00000170 \\.\PhysicalDrive1 status:0
[2020/11/26 21:52:49.610] PHYSICALDRIVE1 size 4000752599040 bytes
[2020/11/26 21:52:49.610] PhyDrv:1 BusType:USB  Removable:0 Size:4000GB(4000752599040) Name:WD Elements 2620
[2020/11/26 21:52:49.611] LogicalDrive:\\.\C: PhyDrive:0 Offset:677380096 ExtentLength:325042831360
[2020/11/26 21:52:49.611] Logical Drive:C  ===> PhyDrive:0
[2020/11/26 21:52:49.611] LogicalDrive:\\.\D: PhyDrive:0 Offset:325720211456 ExtentLength:34359738368
[2020/11/26 21:52:49.612] Logical Drive:D  ===> PhyDrive:0
[2020/11/26 21:52:49.612] LogicalDrive:\\.\G: PhyDrive:1 Offset:134238208 ExtentLength:3966258606080
[2020/11/26 21:52:49.612] Logical Drive:G  ===> PhyDrive:1
[2020/11/26 21:52:49.612] <WD Elements 2620> is filtered for too big for MBR.
[2020/11/26 21:52:49.987] Total 35 languages ...
[2020/11/26 21:52:52.669] #### Now Refresh PhyDrive ####
[2020/11/26 21:52:52.669] 
===================== Enum All PhyDrives =====================
[2020/11/26 21:52:52.670] RegOpenKeyExA <SYSTEM\CurrentControlSet\Services\disk\Enum> Ret:0
[2020/11/26 21:52:52.670] RegQueryValueExA <Count> ret:0  Size:4 Value:2
[2020/11/26 21:52:52.670] GetPhysicalDriveCount: 2
[2020/11/26 21:52:52.670] Logical Drives: 0x4c
[2020/11/26 21:52:52.671] LogicalDrive:\\.\C: PhyDrive:0 Offset:677380096 ExtentLength:325042831360
[2020/11/26 21:52:52.671] C --> 0
[2020/11/26 21:52:52.671] LogicalDrive:\\.\D: PhyDrive:0 Offset:325720211456 ExtentLength:34359738368
[2020/11/26 21:52:52.671] D --> 0
[2020/11/26 21:52:52.672] LogicalDrive:\\.\G: PhyDrive:1 Offset:134238208 ExtentLength:3966258606080
[2020/11/26 21:52:52.672] G --> 1
[2020/11/26 21:52:52.672] Create file Handle:FFFFFFFF \\.\PhysicalDrive0 status:32
[2020/11/26 21:52:52.673] Create file Handle:000002E4 \\.\PhysicalDrive1 status:0
[2020/11/26 21:52:52.673] PHYSICALDRIVE1 size 4000752599040 bytes
[2020/11/26 21:52:52.674] PhyDrv:1 BusType:USB  Removable:0 Size:4000GB(4000752599040) Name:WD Elements 2620
[2020/11/26 21:52:52.674] LogicalDrive:\\.\C: PhyDrive:0 Offset:677380096 ExtentLength:325042831360
[2020/11/26 21:52:52.674] Logical Drive:C  ===> PhyDrive:0
[2020/11/26 21:52:52.674] LogicalDrive:\\.\D: PhyDrive:0 Offset:325720211456 ExtentLength:34359738368
[2020/11/26 21:52:52.674] Logical Drive:D  ===> PhyDrive:0
[2020/11/26 21:52:52.675] LogicalDrive:\\.\G: PhyDrive:1 Offset:134238208 ExtentLength:3966258606080
[2020/11/26 21:52:52.675] Logical Drive:G  ===> PhyDrive:1
[2020/11/26 21:52:52.675] <WD Elements 2620> is filtered for too big for MBR.
[2020/11/26 21:53:43.104] 
################################ Ventoy2Disk 1.0.0.2 ################################
[2020/11/26 21:53:43.105] CmdLine:<-U>
[2020/11/26 21:53:43.105] Control Flag: 0 0 1
[2020/11/26 21:53:43.106] Windows Version : Windows 10 64-bit (Build 18363)
[2020/11/26 21:53:43.106] 
===================== Enum All PhyDrives =====================
[2020/11/26 21:53:43.106] RegOpenKeyExA <SYSTEM\CurrentControlSet\Services\disk\Enum> Ret:0
[2020/11/26 21:53:43.107] RegQueryValueExA <Count> ret:0  Size:4 Value:2
[2020/11/26 21:53:43.107] GetPhysicalDriveCount: 2
[2020/11/26 21:53:43.108] Logical Drives: 0x4c
[2020/11/26 21:53:43.108] LogicalDrive:\\.\C: PhyDrive:0 Offset:677380096 ExtentLength:325042831360
[2020/11/26 21:53:43.108] C --> 0
[2020/11/26 21:53:43.108] LogicalDrive:\\.\D: PhyDrive:0 Offset:325720211456 ExtentLength:34359738368
[2020/11/26 21:53:43.109] D --> 0
[2020/11/26 21:53:43.109] LogicalDrive:\\.\G: PhyDrive:1 Offset:134238208 ExtentLength:3966258606080
[2020/11/26 21:53:43.109] G --> 1
[2020/11/26 21:53:43.109] Create file Handle:FFFFFFFF \\.\PhysicalDrive0 status:32
[2020/11/26 21:53:43.110] Create file Handle:000000C4 \\.\PhysicalDrive1 status:0
[2020/11/26 21:53:43.111] PHYSICALDRIVE1 size 4000752599040 bytes
[2020/11/26 21:53:43.111] PhyDrv:1 BusType:USB  Removable:0 Size:4000GB(4000752599040) Name:WD Elements 2620
[2020/11/26 21:53:43.111] LogicalDrive:\\.\C: PhyDrive:0 Offset:677380096 ExtentLength:325042831360
[2020/11/26 21:53:43.111] Logical Drive:C  ===> PhyDrive:0
[2020/11/26 21:53:43.112] LogicalDrive:\\.\D: PhyDrive:0 Offset:325720211456 ExtentLength:34359738368
[2020/11/26 21:53:43.112] Logical Drive:D  ===> PhyDrive:0
[2020/11/26 21:53:43.112] LogicalDrive:\\.\G: PhyDrive:1 Offset:134238208 ExtentLength:3966258606080
[2020/11/26 21:53:43.112] Logical Drive:G  ===> PhyDrive:1
[2020/11/26 21:53:43.112] <WD Elements 2620> is filtered for too big for MBR.
[2020/11/26 21:53:43.407] Total 35 languages ...
```

**Comment by undefined-moe** [comment]
can only detect local disk when switched to GPT

new log:

```
[2020/11/26 22:41:35.620] 
################################ Ventoy2Disk 1.0.0.2 ################################
[2020/11/26 22:41:35.631] CmdLine:<-U>
[2020/11/26 22:41:35.632] Control Flag: 0 0 1
[2020/11/26 22:41:35.632] Windows Version : Windows 10 64-bit (Build 18363)
[2020/11/26 22:41:35.633] 
===================== Enum All PhyDrives =====================
[2020/11/26 22:41:35.633] RegOpenKeyExA <SYSTEM\CurrentControlSet\Services\disk\Enum> Ret:0
[2020/11/26 22:41:35.633] RegQueryValueExA <Count> ret:0  Size:4 Value:2
[2020/11/26 22:41:35.635] GetPhysicalDriveCount: 2
[2020/11/26 22:41:35.635] Logical Drives: 0x2c
[2020/11/26 22:41:35.636] LogicalDrive:\\.\C: PhyDrive:0 Offset:677380096 ExtentLength:325042831360
[2020/11/26 22:41:35.638] C --> 0
[2020/11/26 22:41:35.639] LogicalDrive:\\.\D: PhyDrive:0 Offset:325720211456 ExtentLength:34359738368
[2020/11/26 22:41:35.639] D --> 0
[2020/11/26 22:41:35.640] LogicalDrive:\\.\F: PhyDrive:1 Offset:449839104 ExtentLength:4000301711360
[2020/11/26 22:41:35.640] F --> 1
[2020/11/26 22:41:35.641] Create file Handle:00000178 \\.\PhysicalDrive0 status:0
[2020/11/26 22:41:35.641] PHYSICALDRIVE0 size 360080695296 bytes
[2020/11/26 22:41:35.643] Create file Handle:00000178 \\.\PhysicalDrive1 status:0
[2020/11/26 22:41:35.645] PHYSICALDRIVE1 size 4000752599040 bytes
[2020/11/26 22:41:35.646] PhyDrv:0 BusType:SATA Removable:0 Size:360GB(360080695296) Name: INTEL SSDSCKKW360H6
[2020/11/26 22:41:35.646] PhyDrv:1 BusType:USB  Removable:0 Size:4000GB(4000752599040) Name:WD Elements 2620
[2020/11/26 22:41:35.647] LogicalDrive:\\.\C: PhyDrive:0 Offset:677380096 ExtentLength:325042831360
[2020/11/26 22:41:35.647] Logical Drive:C  ===> PhyDrive:0
[2020/11/26 22:41:35.647] LogicalDrive:\\.\D: PhyDrive:0 Offset:325720211456 ExtentLength:34359738368
[2020/11/26 22:41:35.647] Logical Drive:D  ===> PhyDrive:0
[2020/11/26 22:41:35.648] LogicalDrive:\\.\F: PhyDrive:1 Offset:449839104 ExtentLength:4000301711360
[2020/11/26 22:41:35.648] Logical Drive:F  ===> PhyDrive:1
[2020/11/26 22:41:35.649] Create file Handle:000000E8 \\.\PhysicalDrive0 status:0
[2020/11/26 22:41:35.649] Read MBR Ret:1 Size:512 code:183
[2020/11/26 22:41:35.650] =========== Partition Table 1 ============
[2020/11/26 22:41:35.650] PartTbl.Active = 0x0
[2020/11/26 22:41:35.651] PartTbl.FsFlag = 0xee
[2020/11/26 22:41:35.651] PartTbl.StartSectorId = 1
[2020/11/26 22:41:35.651] PartTbl.SectorCount = 4294967295
[2020/11/26 22:41:35.652] PartTbl.StartHead = 0
[2020/11/26 22:41:35.652] PartTbl.StartSector = 2
[2020/11/26 22:41:35.652] PartTbl.StartCylinder = 0
[2020/11/26 22:41:35.652] PartTbl.EndHead = 254
[2020/11/26 22:41:35.653] PartTbl.EndSector = 63
[2020/11/26 22:41:35.653] PartTbl.EndCylinder = 3
[2020/11/26 22:41:35.654] =========== Partition Table 2 ============
[2020/11/26 22:41:35.654] PartTbl.Active = 0x0
[2020/11/26 22:41:35.654] PartTbl.FsFlag = 0x0
[2020/11/26 22:41:35.655] PartTbl.StartSectorId = 0
[2020/11/26 22:41:35.655] PartTbl.SectorCount = 0
[2020/11/26 22:41:35.655] PartTbl.StartHead = 0
[2020/11/26 22:41:35.656] PartTbl.StartSector = 0
[2020/11/26 22:41:35.656] PartTbl.StartCylinder = 0
[2020/11/26 22:41:35.656] PartTbl.EndHead = 0
[2020/11/26 22:41:35.656] PartTbl.EndSector = 0
[2020/11/26 22:41:35.657] PartTbl.EndCylinder = 0
[2020/11/26 22:41:35.657] =========== Partition Table 3 ============
[2020/11/26 22:41:35.657] PartTbl.Active = 0x0
[2020/11/26 22:41:35.658] PartTbl.FsFlag = 0x0
[2020/11/26 22:41:35.659] PartTbl.StartSectorId = 0
[2020/11/26 22:41:35.659] PartTbl.SectorCount = 0
[2020/11/26 22:41:35.659] PartTbl.StartHead = 0
[2020/11/26 22:41:35.660] PartTbl.StartSector = 0
[2020/11/26 22:41:35.660] PartTbl.StartCylinder = 0
[2020/11/26 22:41:35.660] PartTbl.EndHead = 0
[2020/11/26 22:41:35.660] PartTbl.EndSector = 0
[2020/11/26 22:41:35.661] PartTbl.EndCylinder = 0
[2020/11/26 22:41:35.661] =========== Partition Table 4 ============
[2020/11/26 22:41:35.662] PartTbl.Active = 0x0
[2020/11/26 22:41:35.662] PartTbl.FsFlag = 0x0
[2020/11/26 22:41:35.662] PartTbl.StartSectorId = 0
[2020/11/26 22:41:35.663] PartTbl.SectorCount = 0
[2020/11/26 22:41:35.663] PartTbl.StartHead = 0
[2020/11/26 22:41:35.663] PartTbl.StartSector = 0
[2020/11/26 22:41:35.663] PartTbl.StartCylinder = 0
[2020/11/26 22:41:35.664] PartTbl.EndHead = 0
[2020/11/26 22:41:35.664] PartTbl.EndSector = 0
[2020/11/26 22:41:35.664] PartTbl.EndCylinder = 0
[2020/11/26 22:41:35.665] Invalid ventoy efi part name
[2020/11/26 22:41:35.665] <WD Elements 2620> is filtered for too big for MBR.
[2020/11/26 22:41:36.622] Total 35 languages ...
```

**Comment by ventoy** [comment]
`<WD Elements 2620> is filtered for too big for MBR.`

Yes, hd1 is bigger than 2TB, so it need to use GPT partition style.

**Comment by undefined-moe** [comment]
but it still doesn't work.

![image](https://user-images.githubusercontent.com/29992205/100365349-5491a680-303a-11eb-99c9-6a7696b64884.png)
![image](https://user-images.githubusercontent.com/29992205/100365366-58bdc400-303a-11eb-96a8-9bccb05b292a.png)

(the log is like the second message)

**Comment by blackcrack** [comment]
@ventoy, Longpanda a suggestion for programming: a warning popup if work with harddisk's with more as 2T and MBR is checked..

**Comment by ventoy** [comment]
This is a bug in Ventoy2Disk.exe. I will fix it in the future release.
Currently you can use VentoyLiveCD to install Ventoy to hd1.
https://www.ventoy.net/en/doc_livecd.html

**Comment by ventoy** [comment]
Please try with 1.0.30

**Comment by undefined-moe** [comment]
works for me.

**Comment by undefined-moe** [comment]
wait i think it created an unknown partition
![image](https://user-images.githubusercontent.com/29992205/102009117-3fbe4e00-3d70-11eb-83c6-8a240b29e878.png)
![image](https://user-images.githubusercontent.com/29992205/102009121-44830200-3d70-11eb-941e-c989ee4c3561.png)

still doesnt work after reformatting to exfat (display a grub2 shell for legacy, efi init fail)

**Comment by undefined-moe** [comment]
![image](https://user-images.githubusercontent.com/29992205/102009274-47cabd80-3d71-11eb-90c7-391787e2bc6e.png)

**Comment by ventoy** [comment]
1. Please use GPT partition style because your disk is bigger than 2TB
2. If you drop into a grub2 shell in Legacy BIOS it may be a BIOS limitation, please refer: [https://www.ventoy.net/en/doc_legacy_limit.html](https://www.ventoy.net/en/doc_legacy_limit.html)

3. What do your mean ` efi init fail`  you can boot into Ventoy's menu normally, but get an init fail when you boot an ISO file ?
Which ISO file did you test? Did you test other ISO files or all the ISO files you tested have the same problem?

**Comment by undefined-moe** [comment]
1. Yes I'm using GPT
2. I'm testing in my virtualbox environment and my 32GB disk works well (also legacy mode), but not with this large disk, so i don't think it caused by bios limitation.
3. cannot load ventoy menu when using efi. virtualbox displays a efi shell.
4. the partition table is incorrect and windows cannot access files in it.

**Comment by ventoy** [comment]
It's a bug, I have reproduce the problem.
I have not fixed it completely, but I add a simple workaround, if you want you can use https://github.com/ventoy/Ventoy/blob/master/INSTALL/Ventoy2Disk.exe
to replace the file in Ventoy-1.0.30 package and install Ventoy.
After install, the partition is still not formated, you need to format it manually(e.g. NTFS) after that Ventoy should be avaliable.

**Comment by ventoy** [comment]
I have fixed the bug.
Please use https://github.com/ventoy/Ventoy/blob/master/INSTALL/Ventoy2Disk.exe  to replace the file in Ventoy-1.0.30 package and retry.

**Comment by undefined-moe** [comment]
I've ran a full reinstall, the partition is correct now, but the it still cannot be recognized.

in virtualbox:  
disk file created using `VBoxManage internalcommands createrawvmdk -filename C:\usb.vmdk -rawdisk \\.\PhysicalDrive` doesn't work, but when I mount it as a usb device with xHCI(usb3.0), I can boot with `fs0:` `EFI\BOOT\BOOTX64.EFI` **manually**.

on my computer:  
after selecting boot from USB device, I just returned to the grub loader installed on my local disk. seems it can't be detected either. :thinking:

partition info:

![image](https://user-images.githubusercontent.com/29992205/102786302-3f5e2c80-43da-11eb-845e-0bfbeabc8183.png)

using `usb.vmdk`:

![image](https://user-images.githubusercontent.com/29992205/102786323-47b66780-43da-11eb-815c-1b6e6b085c62.png)

**Comment by ventoy** [comment]
Did you disable the `secure boot` option in your computer's BIOS settings?

**Comment by undefined-moe** [comment]
Yes I did.

**Comment by taotieren** [comment]
> VBoxManage internalcommands createrawvmdk -filename C:\usb.vmdk -rawdisk \\.\PhysicalDrive

```bash
VBoxManage internalcommands createrawvmdk -filename C:\usb.vmdk -rawdisk \\.\PhysicalDriveN
```
N: Disk number

```bash
# Win + R Open run
 diskmgmt.msc
```

**Comment by undefined-moe** [comment]
`\\.\PhysicalDrive` works for me and it auto select the first usb device.

This problem seems to be fixed. I'll close this issue.
